name: Build Test2

on:
  workflow_dispatch:
  schedule:
    - cron: '10,20,30,40,50 * * * *' # run every day at 16:20 UTC / 8:20 PST
    
concurrency:
  group: ${{ github.workflow }}

jobs:
  build1:

    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2
      with:
        ref: main
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: |
          7.0.x
    - name: Install background
      run: dotnet tool install --global DotnetBackground
    - name: Restore dependencies
      run: dotnet restore Server/
    - name: Build Test
      run: dotnet build Server/ --no-restore
    - name: Test (I:Debug T:Debug R:false)
      run: dotnetbackground run --verbosity normal --project Server/Server.csproj --no-build Server/Debug/net7.0/Server.dll 
    - name: Restore dependencies 2
      run: dotnet restore Client/
    - name: Build Test 2
      run: dotnet build Client/ --no-restore
    - name: Test (I:Debug T:Debug R:false) 2
      run: dotnet run --verbosity normal --project Client/Client.csproj --no-build Client/Debug/net7.0/Client.dll 
